apiVersion: apps/v1
kind: Deployment
metadata:
    name: seminario-deployment
    namespace: workshop
spec:
    replicas: 1
    selector:
        matchLabels:
            app: seminario-app
    template:
        metadata:
            labels:
                app: seminario-app
        spec:
            containers:
                - name: seminario-container
                  image: seminario-dotnet-ms:latest
                  imagePullPolicy: IfNotPresent # Possible values: Always, IfNotPresent, Never
                  ports:
                      - name: http
                        containerPort: 8080
                        protocol: TCP
                      - name: https
                        containerPort: 8443
                        protocol: TCP
                  livenessProbe:
                    httpGet:
                      path: "/health/liveness"
                      port: http
                    initialDelaySeconds: 20
                    timeoutSeconds: 5
                    periodSeconds: 30
                    successThreshold: 1
                    failureThreshold: 5
                  readinessProbe:
                    httpGet:
                      path: "/health/readiness"
                      port: http
                    initialDelaySeconds: 30
                    timeoutSeconds: 60
                    periodSeconds: 30
                    successThreshold: 1
                    failureThreshold: 5
                  resources:
                    requests:
                      memory: "500Mi"
                      cpu: "150m"
                    limits:
                      memory: "1.5Gi"
                      cpu: "500m"
                  env:
                    - name: ConnectionStrings__DefaultConnection
                      valueFrom:
                        secretKeyRef:
                            name: seminario-secret
                            key: connectionString