apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: workshop
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb-configmap
  namespace: workshop
data:
  script.sql: |
    CREATE DATABASE mydb;
    \c mydb;
    CREATE TABLE Items (
      id SERIAL PRIMARY KEY,
      name VARCHAR(255),
      description TEXT,
      quantity INT
    );

    -- Aggiunta di dati iniziali
    INSERT INTO Items (name, description, quantity) VALUES 
    ('Item 1', 'Descrizione del primo item', 10),
    ('Item 2', 'Descrizione del secondo item', 20),
    ('Item 3', 'Descrizione del terzo item', 30);

  init-db.sh: |
    #!/bin/bash
    psql -U postgres -f /docker-entrypoint-initdb.d/script.sql

---      
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_PASSWORD
          value: "mysecretpassword"
        - name: POSTGRES_USER
          value: "postgres"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: init-scripts
        configMap:
          name: postgres-initdb-configmap

# ---
# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: postgres-statefulset
#   namespace: workshop
# spec:
#   serviceName: "postgres"
#   replicas: 1
#   selector:
#     matchLabels:
#       app: postgres
#   template:
#     metadata:
#       labels:
#         app: postgres
#     spec:
#       containers:
#       - name: postgres
#         image: postgres:15
#         env:
#         - name: POSTGRES_PASSWORD
#           value: "mysecretpassword"
#         - name: POSTGRES_USER
#           value: "postgres"
#         volumeMounts:
#         - name: postgres-data
#           mountPath: /var/lib/postgresql/data
#         - name: init-scripts
#           mountPath: /docker-entrypoint-initdb.d
#       volumes:
#       - name: postgres-data
#         persistentVolumeClaim:
#           claimName: postgres-pvc
#       - name: init-scripts
#         configMap:
#           name: postgres-initdb-configmap

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: workshop
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
